class RbsGoose::IO::Example
  @typed_ruby: RbsGoose::IO::TypedRuby
  @refined_rbs: RbsGoose::IO::File
  def self.from_path: (String ruby_path, String rbs_path, String refined_rbs_dir, String base_path) -> RbsGoose::IO::Example
  def initialize: (RbsGoose::IO::TypedRuby typed_ruby, RbsGoose::IO::File refined_rbs) -> void
  def to_h: () -> { typed_ruby: RbsGoose::IO::TypedRuby, refined_rbs: RbsGoose::IO::File }
  attr_reader typed_ruby: RbsGoose::IO::TypedRuby
  attr_reader refined_rbs: RbsGoose::IO::File
end