class RbsGoose::IO::Example
  @typed_ruby: TypedRuby
  @refined_rbs: File
  def self.from_path: (ruby_path: String, rbs_path: String, refined_rbs_dir: String, base_path: String) -> Example
  def initialize: (typed_ruby: TypedRuby, refined_rbs: File) -> void
  def to_h: () -> { typed_ruby: TypedRuby, refined_rbs: File }
  attr_reader typed_ruby: TypedRuby
  attr_reader refined_rbs: File
end