class RbsGoose::IO::File
  @path: untyped
  @base_path: untyped
  @content: untyped
  @type: untyped
  MARKDOWN_REGEXP: Regexp
  def self.from_markdown: (untyped markdown) -> untyped
  def initialize: (path: untyped, ?content: untyped?, ?base_path: untyped?) -> void
  def load_content: () -> untyped
  def absolute_path: () -> untyped
  def type: () -> untyped
  def to_s: () -> String
  def content=: (untyped content) -> untyped
  def write: () -> untyped
  def ==: (untyped other) -> untyped
  attr_reader path: untyped
  attr_reader content: untyped
  attr_reader base_path: untyped
end