class RbsGoose::IO::File
  @path: String
  @base_path: String?
  @content: String
  @type: Symbol
  MARKDOWN_REGEXP: Regexp
  def self.from_markdown: (String markdown) -> File
  def initialize: (path: String, ?content: String?, ?base_path: String?) -> void
  def load_content: () -> String
  def absolute_path: () -> String
  def type: () -> Symbol
  def to_s: () -> String
  def content=: (String content) -> String
  def write: () -> void
  def ==: (Object other) -> bool
  attr_reader path: String
  attr_reader content: String
  attr_reader base_path: String?
end