class RbsGoose::IO::TypedRuby
  @ruby: RbsGoose::IO::File
  @rbs: RbsGoose::IO::File?
  def self.from_path: (String ruby_path, String rbs_path, String base_path) -> RbsGoose::IO::TypedRuby
  def initialize: (RbsGoose::IO::File ruby, RbsGoose::IO::File? rbs) -> void
  def to_s: () -> String
  attr_reader ruby: RbsGoose::IO::File
  attr_reader rbs: RbsGoose::IO::File?
end