class RbsGoose::IO::TypedRuby
  @ruby: untyped
  @rbs: untyped
  def self.from_path: (ruby_path: untyped, rbs_path: untyped, base_path: untyped) -> untyped
  def initialize: (ruby: untyped, rbs: untyped) -> void
  def to_s: () -> ::String
  attr_reader ruby: untyped
  attr_reader rbs: untyped
end
