# Call RbsGoose::TypeInferrer to fix steep type errors.
#   use TbsGoose::Orthoses::FixError, code_dir: 'lib', sig_dir: 'sig' do |config|
#     config.use_open_ai('open_ai_access_token')
#   end
class RbsGoose::Orthoses::FixError
  @loader: Proc
  @code_dir: String
  @sig_dir: String
  def initialize: (Proc loader, ?code_dir: String, ?sig_dir: String) ?{ (Configuration) -> void } -> void
  def call: () -> untyped
end