class RbsGoose::Orthoses::FixError
  @loader: untyped
  @code_dir: String
  @sig_dir: String
  def initialize: (untyped loader, ?code_dir: String, ?sig_dir: String) ?{ () -> void } -> void
  def call: () -> void
end