# Call RbsGoose::TypeInferrer to infer RBS type signatures.
#   use TbsGoose::Orthoses::Infer, code_dir: 'lib', sig_dir: 'sig' do |config|
#     config.use_open_ai('open_ai_access_token')
#   end
class RbsGoose::Orthoses::Infer
  @loader: () -> untyped
  @code_dir: String
  @sig_dir: String
  def initialize: (() -> untyped loader, ?code_dir: String, ?sig_dir: String) ?{ () -> void } -> void
  def call: () -> untyped
end