class RbsGoose::Templates::Base
  @instruction: untyped
  @example_groups: untyped
  def initialize: (instruction: untyped, example_groups: untyped) -> void
  def format: (**untyped args) -> untyped
  def format_system_prompt: () -> untyped
  def format_user_prompt: (**untyped args) -> untyped
  def parse_result: (untyped result) -> untyped
  private def input_template_string: () -> untyped
  private def input_variables: () -> untyped
  private def transform_example_group: (untyped example_group) -> untyped
  private def format_args: (untyped args) -> untyped
  private def prefix: () -> untyped
  private def suffix: () -> String
  private def example_prompt: () -> untyped
  private attr_reader instruction: untyped
  private attr_reader example_groups: untyped
end