class RbsGoose::Templates::InferTemplate < RbsGoose::Templates::Base
  private def input_variables: () -> Array[String]
  private def input_template_string: () -> String
  private def format_args: (untyped args) -> { typed_ruby_list: String }
  private def transform_example_group: (RbsGoose::IO::ExampleGroup example_group) -> { typed_ruby_list: String, refined_rbs_list: String }
end