class RbsGoose::Templates::OneByOneTemplate
  @template: Langchain::Prompt::FewShotPromptTemplate
  def initialize: (instruction: String, examples: Array) -> void
  def format: (String typed_ruby) -> String
  def parse_result: (String result) -> ::Array[IO::File]
  private attr_reader template: Langchain::Prompt::FewShotPromptTemplate
  private def example_prompt: () -> Langchain::Prompt::PromptTemplate
  private def input_template_string: () -> "========Input========\n{typed_ruby}\n\n========Output========"
end