class RbsGoose::Templates::OneByOneTemplate
  @template: untyped
  def initialize: (instruction: untyped, examples: untyped) -> void
  def format: (untyped typed_ruby) -> untyped
  def parse_result: (untyped result) -> ::Array[untyped]
  private attr_reader template: untyped
  private def example_prompt: () -> untyped
  private def input_template_string: () -> "========Input========\n{typed_ruby}\n\n========Output========"
end
