module RbsGoose
  VERSION: "0.1.0"
  self.@configuration: RbsGoose::Configuration
  extend Forwardable
  def self.configure: () { (RbsGoose::Configuration)[self: RbsGoose::Configuration] -> void } -> void
  def self.reset_configuration: () -> untyped
  def self.run: (?code_dir: ::String, ?sig_dir: ::String, ?base_path: untyped) -> untyped
  attr_reader self.configuration: RbsGoose::Configuration
  def self.llm: () -> Langchain::LLM::OpenAI
  def self.instruction: () -> String
  def self.example_groups: () -> Array[untyped]
end