module RbsGoose
  VERSION: String

  self.@configuration: RbsGoose::Configuration

  extend Forwardable

  def self.configure: () { () -> void } -> void

  def self.reset_configuration: () -> void

  def self.run: (?code_dir: String, ?sig_dir: String, ?base_path: String) -> void

  def self.fix_error: (?code_dir: String, ?sig_dir: String, ?base_path: String) -> void

  def self.infer_template: () -> RbsGoose::Templates::InferTemplate

  def self.fix_error_template: () -> RbsGoose::Templates::FixErrorTemplate

  attr_reader self.configuration: RbsGoose::Configuration
end