module RbsGoose
  VERSION: String

  self.@configuration: Configuration

  extend Forwardable

  def self.configure: () { () -> Configuration } -> untyped

  def self.reset_configuration: () -> untyped

  attr_reader self.configuration: Configuration

  def_delegators self.configuration: llm, instruction, examples
end