class RbsGoose::TypeInferrer
  def infer: (untyped target_group) -> untyped
  def fix_error: (untyped target_group) -> untyped
  private def call_llm: (untyped template, untyped format_args) -> untyped
  private def call_llm_complete: (untyped format_args, untyped template) -> untyped
  private def call_llm_chat: (untyped format_args, untyped template) -> untyped
  private def llm_debug: (untyped prompt) { () -> untyped } -> untyped
  private def steep_check: () -> untyped
  private def io_stubs: () -> Array[untyped]
  private def disable_rainbow: () { () -> untyped } -> untyped
end